[phases.setup]
nixPkgs = ["php81", "composer", "php81Packages.pdo", "php81Packages.pdo_pgsql"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.start]
cmds = ["php artisan migrate --force", "php artisan serve --host=0.0.0.0 --port=$PORT"]
